### ISSUE TITLE
Broken development styles link

### ISSUE THREAD

**Issue by drewthoennes** [hubzero/hubzero-cms#104]
The link to development styles and conventions in the contribution guide leads to an empty page.

**Comment by kevinwojo** [comment]
Can you please provide more information?

Where is this link? What should the link resolve to?

**Comment by dthoe19** [comment]
The link is halfway down the Contribution Guide (https://github.com/hubzero/hubzero-cms/wiki/Contribution-Guide) under ##Guidelines. It links to https://hubzero.org/documentation/current/webdevs/codingconventions whereas it should link to https://hubzero.org/documentation/2.1.0/webdevs/conventions .

**Comment by zooley** [comment]
I updated the page and the links should now be fixed.
