### ISSUE TITLE
Default to a new tab for starting tools

### ISSUE THREAD

**Issue by ablekh** [hubzero/hubzero-cms#1063]
From the user experience (UX) perspective, launching a tool (e.g., from Dashboard) in the same tab is IMO a bad idea. It breaks/interrupts the flow and does not provide easy and efficient mechanisms of returning to a starting point or hub’s home. Thus, I wanted to suggest implementing the following (small) feature: 1) default behavior for Run Tool should be open in a new tab (trivially implemented by adding relevant flag to corresponding links’ URL code); 2) to enable the ultimate flexibility, allow hub admins to change the default behavior on a tool-by-tool basis (by introducing an additional configuration element in Control Panel and/or via a separate configuration file; e.g., “/etc/hubzero/tools_start.cfg” with key-value pairs “<tool_name>.start_in_new_tab = False”). Part#2 is optional and can be implemented separately at a later time, if needed. But implementing part#1 is quite important from UX perspective and, considering that it’s extremely easy to do, I see no reason for not improving this aspect.

Please let me know what you think and whether you would agree to implement this soon in the upstream.

-Aleks

**Comment by nkissebe** [comment]
You can right click on the launch button to open in a new tab or window. We do not have plans to change this functionality at this time.
