### ISSUE TITLE
Tools: Incorrect storage indicator value

### ISSUE THREAD

**Issue by ablekh** [hubzero/hubzero-cms#1078]
## Bug Description
Storage indicator in a Tool window is expected to display value (bar size) that would match the actual size of the storage used by the tool. However, this does not happen (as can be seen in an image below).

![HZ_Tools_Incorrect_Storage_Indicator_Value](https://user-images.githubusercontent.com/15176969/58114717-5e755680-7bc6-11e9-8844-470cd41c47cf.png)

## Reproducibility
To reproduce, start a tool (e.g., Workspace) and observe the area to the right of Storage (manage) text in the bottom left corner of the tool window. Notice that the bar size does not match the actual storage size displayed as X%.

## Environment

| Question               | Answer
| ------------------------| -------
| HUBzero version         | 2.2.15
| PHP version             | 5.6.25
| OS & version            | RHEL 6

## Additional Context (optional)
None

**Comment by nkissebe** [comment]
This appears to be an issue only for a value of 0% used.

**Comment by nkissebe** [comment]
Fixed in 3f7a8e0661357cd524ee905212f949b2a780d473
