### ISSUE TITLE
API endpoints not working?

### ISSUE THREAD

**Issue by axfelix** [hubzero/hubzero-cms#1287]
On a fresh standup (via vagrant, https://github.com/axfelix/hubzero-vagrant), trying to see what API endpoints I can access based on the documentation available from `https://localhost/developer/api/endpoint/projects:`

Some of the listed endpoints return 404s, e.g.:
`https://localhost/projects/list`

Is this documentation up to date or is something broken in my standup?

**Comment by jmloewen** [comment]
I'm also experiencing this issue - do some of these endpoints require additional configuration or set-up?  Is there some sort of data load or configuration required?  Upon navigation to certain pages, I get either a 404 or a 500 error.

**Comment by zooley** [comment]
Not sure if you're still having issues but it should be noted that URLs in the API documentation (e.g., https://localhost/developer/api/endpoint/projects) are relative to the API base (`{your host}/api`). The project list should be:

`https://localhost/api/projects/list`

Not:

`https://localhost/projects/list`
