### ISSUE TITLE
HUBzero website links issues between old and new (help.) URLs

### ISSUE THREAD

**Issue by yvanlebras** [hubzero/hubzero-cms#155]
Dear HUBzero team,

Following my message on Twitter, and your response, I open an issue concerning the fact that all Google HUBzero old links (hubzero.org) are not pointing the new URL (help.hubzero.org)... Maybe you can redirect this ?

Cheers,

Yvan

**Comment by zooley** [comment]
This was fixed some time ago. Simply forgot to close this.
