### ISSUE TITLE
No opened tickets visible from backend or frontend

### ISSUE THREAD

**Issue by yvanlebras** [hubzero/hubzero-cms#156]
Dear HUBzero team,

I encounter an issue.. Apparently a bug. When creating a new ticket on a fresh HUBzero installation (from 2.1.2.0 VMWare VM OR  Dockerized HUBzero,) this ticket seems to be hidden... No opened ticket appears on the myhub/support/tickets URL even on the backend even if we can see on the backend control panel that there is one...
![backend_ticket](https://user-images.githubusercontent.com/7910679/31080439-003e440e-a789-11e7-842a-cd612184014b.PNG)
![backend_ticket_2](https://user-images.githubusercontent.com/7910679/31080444-02b200ae-a789-11e7-95e1-b0432f5ddba3.PNG)

**Comment by zooley** [comment]
This is a known issue with the default data that populates some of the Support database tables. Depending on what version you're running:

Go to the "Queries" submenu item of the Support Component. Look for a "reset" button. If there, press it.

If the button is not there, then you're running an older version of the CMS and will have tor set manually. This can be done by clearing all records in the `#__support_queries` and `#__support_query_folders` database tables. The system will re-install the default queries and folders.
