### ISSUE TITLE
A Few HubZero Questions

### ISSUE THREAD

**Issue by jwtouron** [hubzero/hubzero-cms#1680]
Hello,

According to the documentation, Hubzero is officially supported on RHEL 7 and CentOS 7, both of which will stop receiving support sometime next year.

Also, according to the roadmap, a HubZero Docker image will possibly be available at some point.

I'm trying to get HubZero working on CentOS Stream 9, in a docker container, from the source in this repo.

Given all that, I have 3 questions:

1) Are you planning on supporting other operating systems in the near future?
2) Is support for a HubZero Docker image still on the roadmap?
3) Are there instructions available somewhere for installing from the source code in this repo?

Thank you.

**Comment by nkissebe** [comment]
Rocky 9 will probably be our next target. Most of our current development is for our hosted services now, I am not sure how much will be packaged for public consumption.

Can this repo be used on its own?  It hasn't been self bootstrapping in quite some time, I would not recommend trying.

Will there be a docker image?  Probably, for the basic hubzero instance (this excludes tool execution, which is arguably the primary feature).

**Comment by jwtouron** [comment]
Thank you for taking the time to answer my questions.
