### ISSUE TITLE
[Request] Universal DOI representation throughout the CMS

### ISSUE THREAD

**Issue by kevinwojo** [hubzero/hubzero-cms#33]
It would be way cool to have a standardized way to represent DOIs on throughout the hub. I've attached an example of a Github-style badge used to communicate the DOI and resolve it when clicked.

![screenshot from 2017-01-24 09-47-04](https://cloud.githubusercontent.com/assets/9081680/22251864/4e283632-e21a-11e6-980e-1605b6fc3594.png)

http://pages.tacc.utexas.edu/~eijkhout/istc/istc.html

**Comment by zooley** [comment]
Interesting idea. We really do need to be more consistent in how we display various elements...

**Comment by nkissebe** [comment]
We don't currently have plans to implement this any time soon. Closing issue to keep list more actionable.
