### ISSUE TITLE
Integrate Slack inside of Hubzero's platform

### ISSUE THREAD

**Issue by cfrist** [hubzero/hubzero-cms#36]
Use-cases: 
- A file shared in a slack channel can be imported into a Group or Project. 
- Discussions can be transferred between Slack and Hubzero notes, blogs, other communication features
- Add web hooks for cms events to notify Slack channel

**Comment by andyburnett** [comment]
It would also be great to be able to automagically create a slack group when creating a new HZ group

**Comment by yvanlebras** [comment]
Hi @cfrist @andyburnett . Testing the slack integration on the last HUBzero VM version http://packages.hubzero.org/vmware/hubzerovm-2.1.2.0-amd64-vmware.tar.gz .. and it seems to work. When a ticket is open on HUBzero, a new post is created on the dedicated Slack channel... Cool ! Thanks !

**Comment by nkissebe** [comment]
We do not have plans to further develop this feature in the near future.
