### ISSUE TITLE
Modified Date is not shown for some publications

### ISSUE THREAD

**Issue by kevinwojo** [hubzero/hubzero-cms#44]
https://purr.purdue.edu/support/ticket/1221

Megan Dale (mdale)	3:02 pm 01 Dec 2016

1) What was the user trying to do?
Show the dates of when files that are added or changed

2) What did they expect to happen?
The file directory in your project should automatically display the last modified date for each file, and should show you the full version history for that file if you click on the date.

3) What actually happened?
Sometimes a file directory shows N/A next to a file instead of the modified date.  If I click the "Modified" heading at the top of the directory to sort by modified date, any N/A's in the list resolve to actual dates.

**Comment by nkissebe** [comment]
ticket was closed
