### ISSUE TITLE
Config interface for adjusting API rate limiting

### ISSUE THREAD

**Issue by kevinwojo** [hubzero/hubzero-cms#49]
Create an interface on the backend to adjust API rate limiting.

**Comment by kevinwojo** [comment]
I think @tigerh and I will work on this together.

**Comment by zooley** [comment]
This was added to the master branch. Maybe back-port? 830d3fcfa5b4218f8f5e0c0c72b21777511423a2

**Comment by zooley** [comment]
And I back-ported the change to the 2.1.x branch.
