### ISSUE TITLE
Ability to disable normal hub login if account is already linked

### ISSUE THREAD

**Issue by kevinwojo** [hubzero/hubzero-cms#56]
If an account is linked to another login method like Facebook, Google, LinkedIn or an institution through Shibboleth, allow the user to disable the login method with a hub password;  this should make the account never expire.  The rationale is that it minimizes the attack surface of accounts and is less hassle for users (fewer passwords to keep changing).  Also, if the other login methods support more secure logins like Google's 2-factor authentication, the hub password login method is a liability.  Besides making sense on its own, this feature is needed before we can handle higher security requirements such as hubs with more than limited data sets (HIPAA).

From Pascal.

**Comment by nkissebe** [comment]
This issue is being tracked internally.
