### ISSUE TITLE
Current installation process?

### ISSUE THREAD

**Issue by mathuaerknedam** [hubzero/hubzero-cms#612]
I created a new Debian 8 VM and followed the installation instructions for 2.2.0 at https://help.hubzero.org/documentation/220/installation/debian/install/ .

While it appears that the main CMS installs fine and works, some components do not. Notably, the configuration scripts error and dump a stack trace for Forge, VZ (container system), Maxwell, Workspace, Metrics, Rappture, and submit-server.

I'm guessing this is due to the 2.2.0 docs not reflecting the current state of 2.2.9... I noticed that https://github.com/hubzero/hubzero-cms/issues/70 states that the packages are the official installation and update mechanism, is there a plan to update the installation docs?

Also, considering that Debian 8 only supports PHP 5.6 and that's no longer getting security updates as of Jan 1 2019, I'm guessing that the project will either be providing a backported PHP 7 package, or will be moving to Debian 9 as the supported platform. Is there any sort of timeframe on when that will happen? It's pretty old, but the latest info I've found on the topic is in https://github.com/hubzero/hubzero-cms/issues/63: "We have not yet started work on determining whether Debian 9 will be able to host a complete hubzero environment and it will certainly not install or run on it until that work is begun."

Thanks!

**Comment by nkissebe** [comment]
Can you provide details of the errors (I am guessing the hubzero-cli package just needs to be rebuilt).  Debian will provide PHP 5.6 security fixes for the duration of Debian 8's support life. We still do not have firm plans for a transition to Debian 9. Our own most recent new installations have been on CentOS/Redhat 6.

**Comment by mathuaerknedam** [comment]
Here are a few.

Forge:

    root@hubzero22x2:~# hzcms configure forge --enable
    Traceback (most recent call last):
      File "/usr/bin/hzcms", line 7623, in <module>
        args.func(args)
      File "/usr/bin/hzcms", line 2821, in _forgeConfigure
        forgeConfigure(args.enable)
      File "/usr/bin/hzcms", line 2828, in forgeConfigure
        dbHost = hubzero.config.webconfig.getWebConfig('host', hubname)
    AttributeError: 'module' object has no attribute 'getWebConfig'

Workspace:

    root@hubzero22x2:~# hubzero-app install --publish /usr/share/hubzero/apps/workspace-1.3.hza
    Traceback (most recent call last):
      File "/usr/bin/hubzero-app", line 700, in <module>
        Hubzero_App().dispatch()
      File "/usr/bin/hubzero-app", line 515, in dispatch
        self.changeuid()
      File "/usr/bin/hubzero-app", line 496, in changeuid
        _,_,uid,gid,_,_,_ = pwd.getpwnam("apps")
    KeyError: 'getpwnam(): name not found: apps'

Metrics:

    root@hubzero22x2:~# hzcms configure metrics --enable
    Traceback (most recent call last):
      File "/usr/bin/hzcms", line 7623, in <module>
        args.func(args)
      File "/usr/bin/hzcms", line 4011, in _mwMetrics
        mwMetrics(args.enable)
      File "/usr/bin/hzcms", line 4017, in mwMetrics
        dbPW = hubzero.config.webconfig.getWebConfigOption('host', hubname)
    UnboundLocalError: local variable 'hubname' referenced before assignment

There are a variety of other warnings or errors displayed during package installation or the configuration step. Since these are apparently unexpected, I can go back and make better documentation, submitting an issue after each one to avoid compounding errors. I'll wait to see if there's some more general fix that should be applied first (like rebuilding the hubzero-cli package).

**Comment by nkissebe** [comment]
Try now. hubzero-cli_2.2.47 should be available in the julian-deb8 repo

**Comment by mathuaerknedam** [comment]
Thanks. I confirmed that resolved the problem with forge, didn't affect the problem with workspace, and caused metrics to produce another error. I decided to start a clean install to make sure I didn't introduce any compounding problems, and encountered my first possible problem installing hubzero-apache2:

    hostname: Name or service not known
    make-ssl-cert: Could not get FQDN, using "hzexample.iti.lab".

I this test system isn't on the internet, andis only accessible via vpn. It looked like it made the right call and moved on.

However, the same message returned while installing openldap.

    ...
    Preconfiguring packages ...
    hostname: Name or service not known
    hostname: Name or service not known
    ...
    Setting up nslcd (0.9.4-3+deb8u2) ...
    hostname: Name or service not known
    hostname: Name or service not known
    Warning: The home dir /var/run/nslcd/ you specified can't be accessed: No such file or directory
    Adding system user `nslcd' (UID 111) ...
    Adding new group `nslcd' (GID 118) ...
    Adding new user `nslcd' (UID 111) with group `nslcd' ...
    Not creating home directory `/var/run/nslcd/'.
   ....

And then in the post-install setup:
    root@hzexample2:~# hzldap init dc=example,dc=com
    getting current info via slapcat
    found olcDbDirectory for for olcDatabase={1}mdb: /var/lib/ldap
    found olcSuffix: dc=nodomain
    Changing olcSuffix to dc=example,dc=com
    Modifying olcSuffix to [dc=example,dc=com]
    removing 'olcAccess' from dn: olcDatabase={1}mdb,cn=config
    removing 'olcTLSCertificateFile' from dn: olcDatabase={1}mdb,cn=config
    removing 'olcTLSCertificateKeyFile' from dn: olcDatabase={1}mdb,cn=config
    adding olcAccess entires
    olcRootPW already exists, changing it
    attempting ldap bind to localhost
    ldapManagerUserDN=cn=Manager,dc=example,dc=com adminUserPW=bUeoAocG51
    adding root container
    adding admin user
    adding sync user
    adding search user
    adding users root ou container
    adding groups root ou container
    unbinding from ldap dc=example,dc=com
    writing out /etc/nslcd.conf
    /usr/sbin/service nslcd stop
    /usr/sbin/service nslcd start
    /usr/sbin/service nscd stop
    /usr/sbin/service nscd start
    writing out /etc/nsswitch.conf
    Traceback (most recent call last):
      File "/usr/bin/hzldap", line 1187, in <module>
        rc = args.func(args)
      File "/usr/bin/hzldap", line 1028, in _init_ldap
        uri = "ldap://" + socket.getaddrinfo(socket.gethostname(), 0, 0, 0, 0, socket.AI_CANONNAME)[0][3]
    socket.gaierror: [Errno -2] Name or service not known

I don't know if the name/server complaints are merely informational, or if the messages about /var/run/nslcd/  are important, but when I saw the backtrace I wanted to stop and report back.

Thanks for your help.

**Comment by nkissebe** [comment]
You need to have a resolvable hostname. Per documentation "Set Hostname"  and "Fix Hosts" sections. I've never actually seen that message before, but that seems to be the probable cause.

**Comment by mathuaerknedam** [comment]
My problem ended up being that the hostname in /etc/hosts and /etc/hostname didn't match. After starting over with a clean VM, I've not seen any problems until installing OpenVZ.

```
Setting up linux-image-2.6.32-openvz-042stab134.8-amd64 (1) ...

 Hmm. There is a symbolic link /lib/modules/2.6.32-openvz-042stab134.8-amd64/build
 However, I can not read it: No such file or directory
 Therefore, I am deleting /lib/modules/2.6.32-openvz-042stab134.8-amd64/build


 Hmm. The package shipped with a symbolic link /lib/modules/2.6.32-openvz-042stab134.8-amd64/source
 However, I can not read the target: No such file or directory
 Therefore, I am deleting /lib/modules/2.6.32-openvz-042stab134.8-amd64/source

depmod: WARNING: could not open /lib/modules/2.6.32-openvz-042stab134.8-amd64/modules.builtin: No such file or directory
Examining /etc/kernel/postinst.d.
run-parts: executing /etc/kernel/postinst.d/apt-auto-removal 2.6.32-openvz-042stab134.8-amd64 /boot/vmlinuz-2.6.32-openvz-042stab134.8-amd64
run-parts: executing /etc/kernel/postinst.d/initramfs-tools 2.6.32-openvz-042stab134.8-amd64 /boot/vmlinuz-2.6.32-openvz-042stab134.8-amd64
update-initramfs: Generating /boot/initrd.img-2.6.32-openvz-042stab134.8-amd64
depmod: WARNING: could not open /var/tmp/mkinitramfs_33gw6z/lib/modules/2.6.32-openvz-042stab134.8-amd64/modules.builtin: No such file or directory
run-parts: executing /etc/kernel/postinst.d/zz-update-grub 2.6.32-openvz-042stab134.8-amd64 /boot/vmlinuz-2.6.32-openvz-042stab134.8-amd64
```
And a bit later:
```
Setting up vzctl (4.9.4-2) ...
Job for vz.service failed. See 'systemctl status vz.service' and 'journalctl -xn' for details.
invoke-rc.d: initscript vz, action "start" failed.
```
systemctl status revealed
```
Feb 08 14:11:53 hzexample3.iti.lab vz[72089]: Running kernel is not an OpenVZ kernel
Feb 08 14:11:53 hzexample3.iti.lab systemd[1]: vz.service: control process exited, code=exited status=6
```
There didn't appear to be anything relevant from journalctl.

I wasn't hopeful, but I wanted to see what the hzcms configure output:
```root@hzexample3:~# hzcms configure openvz --enable
enabling openvz
checking /etc/default/grub
checking /etc/modules
checking /etc/sysctl.conf
setting net.ipv4.ip_forward=1
Traceback (most recent call last):
  File "/usr/bin/hzcms", line 7627, in <module>
    args.func(args)
  File "/usr/bin/hzcms", line 4963, in _openvzConfigure
    openvzEnable()
  File "/usr/bin/hzcms", line 5026, in openvzEnable
    rc = lineinfile(path = '/etc/modprobe.d/openvz.conf', regexp = "^\s*options\s+nf_conntrack\s+ip_conntrack_disable_ve0\s*=.*$", line = "options nf_conntrack ip_conntrack_disable_ve0=0")
  File "/usr/bin/hzcms", line 6779, in lineinfile
    with open(path, 'r+') as f:
IOError: [Errno 2] No such file or directory: '/etc/modprobe.d/openvz.conf'
```
Since the status message mentioned the kernel wasn't OpenVZ, I reboot to see if that would help. After confirming no boot errors, and that the OpenVZ kernel (2.6.32-openvz-042stab134.8-amd64) was running, I checked the status again:
```
root@hzexample3:~# systemctl status vz.service
Failed to get D-Bus connection: Unknown error -1
```
At this point, hzcms configure dumps the same stack trace as before the reboot. 

[Here's the full package install log.](https://gist.github.com/mathuaerknedam/e7065517328d86b46a81ebe2166b7497)

**Comment by nkissebe** [comment]
One of the issues is that you are trying to use systemd service controls, part of the hubzero install should be reverting Debian 8 to be sysvinit based (as required by the OpenVZ kernel) rather than systemd.

You might try manually adding the file /etc/modprobe.d/openvz.conf with one line:
options nf_conntrack ip_conntrack_disable_ve0=0

Then reboot. You should be able to get a vz service status from "service vz status"

**Comment by imneedham** [comment]
Awesome, hzcms configure now completes without a problem. Does this mean that the warnings displayed earlier, during the package installation, don't matter?

As far as I know, I've only followed the steps in the documentation. Is the addition of /etc/modprobe.d/openvz.conf a step missing from the package installation, or just a band-aid on a deeper problem?

**Comment by nkissebe** [comment]
The warnings are normal.  I think its just a bug that hzcms doesn't create the file if it is missing, i think the file is automatically created in some circumstances (or maybe just on redhat installs). I will fix hzcms to create the file if it is missing rather than throw an error.

**Comment by imneedham** [comment]
There appears to be an error enabling the maxwell client:
```
root@hzexample3:~# hzcms configure mw2-client --enable
enabling mw2-client
key already in /var/www/.ssh/authorized_keys
rewriting /var/www/.ssh/authorized_keys with new SSH key options
/usr/sbin/service expire-sessions restart
expire-sessions: unrecognized service
```
I'm guessing the workaround is to install hubzero-expire-sessions and restart the service, but I don't know if there's anything less obvious that needs to happen as well.

**Comment by nkissebe** [comment]
Exactly right. Docs need to be updated, it used to be a package dependency and done automatically.

**Comment by imneedham** [comment]
Next up:
```
root@hzexample3:~# apt-get install hubzero-mw2-service
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package hubzero-mw2-service
```
The next step in the docs involves mkvztemplate, which is part of hubzero-mw2-exec-service, which isn't yet installed and has a similar name. Is that it? Is there anything else missing that needs installed for the Maxwell Service step?

**Comment by nkissebe** [comment]
Yup hubzero-mw2-exec-service (package changed names, missed it in the docs).

**Comment by erichhuebner** [comment]
Docs updated.  https://help.hubzero.org/documentation/220/installation/debian/install

**Comment by imneedham** [comment]
I'm not to the Rappture step, and everything appears to have run without errors. The test section contains the command "use rappture", but I don't see any command 'use'. I thought maybe it was something that needed to be run from within the workspace, so logged in to HubZero, went to tools, and clicked the icon to launch Workspace. Nothing happens, except a little red box that contains "Failed to invoke session". 

In hindsight, I should have noticed this earlier. The Workspace installation page says to "launch", but I only clicked the "workspace" link that opened that tool's page (.../tools/workspace).

I'm guessing that these are two different issues, and not related, but the workspace page doesn't include any trouble shooting steps in the event that the test fails. I'm not seeing any clues under /var/log/hubzero/ or /var/log/hubzero-cms/. How should I proceed?

**Comment by healthlink-sdsu** [comment]
Chiming on a similar issue.

Deploying on CentOS6 w/end goal running GABBs

Near the end, the Workspace install yields this:

`KeyError: 'getpwnam(): name not found: apps'`

BTW the PDF shows the command as 

`sudo hubzero-
app install --publish /usr/share/hubzero/apps/workspace-1.3.hza`

actual output/stack trace:

`$ sudo hubzero-app install --publish /usr/share/hubzero/apps/workspace-1.3.hza
Traceback (most recent call last):
  File "/usr/bin/hubzero-app", line 700, in <module>
    Hubzero_App().dispatch()
  File "/usr/bin/hubzero-app", line 515, in dispatch
    self.changeuid()
  File "/usr/bin/hubzero-app", line 496, in changeuid
    _,_,uid,gid,_,_,_ = pwd.getpwnam("apps")
KeyError: 'getpwnam(): name not found: apps'
[paulfern@hubzero-22-gabbs ~]$ sudo hubzero-app
Traceback (most recent call last):
  File "/usr/bin/hubzero-app", line 700, in <module>
    Hubzero_App().dispatch()
  File "/usr/bin/hubzero-app", line 515, in dispatch
    self.changeuid()
  File "/usr/bin/hubzero-app", line 496, in changeuid
    _,_,uid,gid,_,_,_ = pwd.getpwnam("apps")
KeyError: 'getpwnam(): name not found: apps'`

Thanks.
