### ISSUE TITLE
Travis CI produces inconsistent results when CodeSniffer is ran

### ISSUE THREAD

**Issue by kevinwojo** [hubzero/hubzero-cms#62]
https://travis-ci.org/hubzero/hubzero-cms/builds/194885635 supposedly contained the same files as https://travis-ci.org/hubzero/hubzero-cms/builds/194928112

**Comment by kevinwojo** [comment]
@zooley just mentioning you for this.

**Comment by zooley** [comment]
I think we eventually figured out this had to do with the time files were committed (and, thus, found and passed to the code sniffer). So, ultimately, the same set of files were not being passed to the code sniffer due to variances in last commit timestamps.
