### ISSUE TITLE
Settle on a definitive update mechanism for HUBzero CMS

### ISSUE THREAD

**Issue by kevinwojo** [hubzero/hubzero-cms#70]
From https://hubzero.org/support/ticket/10316:

hzcms is meant for the Debian or Redhat package versions of the CMS. 

The manner in which we are distributing the CMS moving forward is a discussion that is happening internally. 

It would be my hope to have the Debian and Redhat packages created more frequently so we can rely on them for distributing the code. In that manner, updating would be simply a `yum update`. There may be some downsides to that approach that I have not discovered yet, but this is an active conversation in the Hubzero development group.

**Comment by kevinwojo** [comment]
The update component will no longer be shipped in core.

**Comment by JackS9** [comment]
Is there any downside to switching to using GitHub, composer, and muse to update the CMS?  We've started down this route on our new dev server, and I could use advice on a workflow for migrating changes, especially local development (Components, Modules, Supergroups,...) on /app, from our dev server to our production server.

**Comment by kevinwojo** [comment]
The downside for using Github for your pipeline would be that we will not ship any mechanism to manage the update for you. You'll have to develop and maintain your own pipeline.

The package is the Hubzero-assisted update process moving forward. The code is a snapshot in time of the git repository and migrations are ran with muse and composer dependencies are already pre-packaged.

In our setup, we use git and have a set of scripts which sets the environment for our needs. The scripts are not necessarily generalized at this point and no effort has been designated for that task.

You could use the package to update /core and use git within your /app directory to manage your customized extentions.

**Comment by JackS9** [comment]
I'd really like to learn a workflow/pipeline (for both app and core) that's as close as possible to what you all follow - at least on our dev machine.

**Comment by JackS9** [comment]
Yikes, I just realized that I ran the muse migrations (on our dev machine) before I checked out the 2.1.3 branch, which means I ran the migrations for the master branch (checked out by default after the git clone).  How can I roll those back and rerun the 2.1.3 migrations?

**Comment by nkissebe** [comment]
Closing this issue.
