### ISSUE TITLE
Inconsistent Time Representation Across the Hub

### ISSUE THREAD

**Issue by kevinwojo** [hubzero/hubzero-cms#82]
https://hubzero.org/support/ticket/5416

> David Lomas (dsl101) 7:57 am 20 Jun 2014

1.2.2 Thu, 19 Jun 2014

Recently updated this hub to fix the email HTML and Newsletter timezone issues - they're all gone, but we're still seeing problems in Group Calendar I'm afraid. I'll try to explain carefully, but it's pretty intricate...

I created 3 test events in a group calendar - here are the names, and you should be able to see what I put in the date / time / timezone fields:

Test1 01:00 UTC
Test2 05:00 UTC+1
Test3 09:00 UTC-5

The first snag here is that the timezone field here is a little confusing for people on daylight saving - in the UK we're normally on UTC, but in the summer we move to UTC+1. So, should I enter UTC or UTC+1?

Having entered them as above, this is what I see in the month view of the calendar:

2a Test1 01:00 UTC
6a Test2 05:00 UTC+1
10a Test3 09:00 UTC-5

I'm presuming those '2a, 6a, 10a' are intended to be the start times (e.g. 2am, 6am, 10am) in my local timezone? In which case, only the first entry is accurate - a 1am UTC event would be 2am for me. The others are wrong - 5am UTC+1 would be 5a for me, and 9am UTC-5 would also be 3p for me. It looks like it is assuming all events are in UTC, and just adding on the 1 hour for my current timezone, which is effectively UTC+1.

When I open up those events, this is the detail view I see:

Test1 01:00 UTC: 1:00 am BST
Test2 05:00 UTC+1: 5:00 am CEST
Test3 09:00 UTC-5: 9:00 am EDT

I don't think any of those are correct:

- The first one isn't 1am BST, it's 1am GMT (2am BST)
- The second one isn't 5am CEST, it's 5am BST (6am CEST)
- The third one isn't 9am EDT, it's 9am EST (10am EDT)

It's also strange that in the month view I get something approaching my local timezone, but in the detail view I get an (incorrect) version of the timezone for the event.

**Comment by kevinwojo** [comment]
The following file is the complete history of the HUBzero ticket. We will be opening this issue out to the community.

[HUBzero - Support_ Ticket #5416.pdf](https://github.com/hubzero/hubzero-cms/files/807095/HUBzero.-.Support_.Ticket.5416.pdf)

**Comment by nkissebe** [comment]
Closing this as an old issue. There have been a couple commits related to timezones that hopefully resolve this issue. Having the daylight savings time selection is indeed confusing and more work is surely needed.
