### ISSUE TITLE
Add author of a collection or post in search results

### ISSUE THREAD

**Issue by cfrist** [hubzero/hubzero-cms#89]
Suggested by Hubzero Foundation member, Jack Allen Smith

Would it be possible to label Collections prefixed/suffixed with the owner of the collection to distinguish collections with the same name when browsing/searching collections across the site? Collections named Books, Articles, Conferences, News,... are quite common across multiple users and groups.

**Comment by nkissebe** [comment]
We do not have plans to implement this feature in the near future.
